
# References {-}

1). Ferrero, V. (2013). The Effectiveness of Using Pace, eFG%, TOV ... - CAE Users. Retrieved from http://homepages.cae.wisc.edu/~ece539/fall13/project/Ferrero_rpt.pdf

2). Knutson, T. (2013, January 24). A Look at Pace in Football. Retrieved from https://bitterandblue.sbnation.com/2013/1/24/3908816/football-soccer-analytics-pace

3). Knutson, T. (2015, January 05). Pace and Margin for Error. Retrieved from https://statsbomb.com/2013/11/pace-and-margin-for-error/

4). Minkus, K. (2017, March 09). Examining Pace in MLS. Retrieved from http://www.americansocceranalysis.com/home/2017/3/9/examining-pace-in-mls

5). Lawrence, T. (2015, November 6). Europe’s Most Direct Teams – Deep xG. Retrieved from https://deepxg.com/2015/11/06/europes-most-direct-teams/

6). Batorski, E. (2020, April 07). Ball possession in football - how it's calculated and how it matters: STATSCORE - News Center. Retrieved from https://blog.statscore.com/ball-possession-in-football-how-its-calculated-and-how-it-matters/

7). Yu, D., Boucher, C., Bornn, L., & Javan, M. (2019, February). Playing Fast Not Loose: Evaluating team-level pace of play in ice hockey using spatio-temporal possession data. Retrieved from https://arxiv.org/pdf/1902.02020.pdf

8). Gibney, A. (2017, October 02). Ranking Ligue 1 Sides on Their Defensive Strength. Retrieved from https://bleacherreport.com/articles/2321750-ranking-the-ligue-1-sides-on-their-defensive-strength

9). Yi, Q., Groom, R., Dai, C., Liu, H., & Gómez Ruano, M. Á. (2019, November 19). Differences in Technical Performance of Players From 'The Big Five' European Football Leagues in the UEFA Champions League. Retrieved from https://www.frontiersin.org/articles/10.3389/fpsyg.2019.02738

10). Nalton, J. (2019, September 13). Play Up Or Play Out: The Myths And Legends Of Playing Out From The Back. Retrieved from https://worldfootballindex.com/2019/09/playing-out-from-the-back-tactics-analysis-guardiola-lillo/

11). Spencer, J. (2017, November 22). Stats Reveal Just How Suited New #1 Ederson Is to Pep Guardiola's Man City System. Retrieved from https://www.90min.com/posts/5833855-stats-reveal-just-how-suited-new-1-ederson-is-to-pep-guardiola-s-man-city-system

12). https://www.washingtonpost.com/news/fancy-stats/wp/2014/10/16/two-of-soccers-most-dangerous-passes/

13). https://www.espn.com/soccer/english-premier-league/story/3945761/why-playing-out-from-the-back-has-brought-mixed-results-for-premier-league-clubs

14). https://www.mirror.co.uk/sport/football/news/pep-guardiola-explains-axing-joe-13445300

15). https://worldfootballindex.com/2019/09/playing-out-from-the-back-tactics-analysis-guardiola-lillo/

16). https://themastermindsite.com/2019/08/20/playing-out-from-the-back-full-session-plan-and-key-coaching-points/

17). https://bleacherreport.com/articles/2790722-why-kepa-arrizabalaga-is-the-most-expensive-keeper-in-the-world

18). https://www.youtube.com/watch?v=1JBDCilBnas

19). https://www.skysports.com/football/news/11667/11278517/jose-mourinho-under-pressure-to-attack-when-manchester-united-host-liverpool

20). https://www.coachbetter.com/new-posts/soccer-tactic-why-is-the-4-1-4-1-the-best-formation/

21).https://spielverlagerung.com/2016/10/19/mourinhos-midfield-pressing-and-6-3-1-halts-klopps-side/

22). https://www.nature.com/articles/s41597-019-0247-7

